// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: mobil.sql

package db

import (
	"context"
	"database/sql"
)

const createMobil = `-- name: CreateMobil :one
INSERT INTO mobil (
  nama, 
  deskripsi,
  kategori_id,
  user_id,
  gambar,
  trf_6jam,
  trf_12jam,
  trf_24jam,
  seat,
  top_speed,
  max_power,
  pintu,
  gigi
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
) RETURNING id, nama, deskripsi, kategori_id, gambar, user_id, trf_6jam, trf_12jam, trf_24jam, seat, top_speed, max_power, pintu, gigi, created_at
`

type CreateMobilParams struct {
	Nama       string         `json:"nama"`
	Deskripsi  sql.NullString `json:"deskripsi"`
	KategoriID int64          `json:"kategori_id"`
	UserID     string         `json:"user_id"`
	Gambar     sql.NullString `json:"gambar"`
	Trf6jam    int64          `json:"trf_6jam"`
	Trf12jam   int64          `json:"trf_12jam"`
	Trf24jam   int64          `json:"trf_24jam"`
	Seat       sql.NullInt64  `json:"seat"`
	TopSpeed   sql.NullInt64  `json:"top_speed"`
	MaxPower   sql.NullInt64  `json:"max_power"`
	Pintu      sql.NullInt64  `json:"pintu"`
	Gigi       sql.NullString `json:"gigi"`
}

func (q *Queries) CreateMobil(ctx context.Context, arg CreateMobilParams) (Mobil, error) {
	row := q.db.QueryRowContext(ctx, createMobil,
		arg.Nama,
		arg.Deskripsi,
		arg.KategoriID,
		arg.UserID,
		arg.Gambar,
		arg.Trf6jam,
		arg.Trf12jam,
		arg.Trf24jam,
		arg.Seat,
		arg.TopSpeed,
		arg.MaxPower,
		arg.Pintu,
		arg.Gigi,
	)
	var i Mobil
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Deskripsi,
		&i.KategoriID,
		&i.Gambar,
		&i.UserID,
		&i.Trf6jam,
		&i.Trf12jam,
		&i.Trf24jam,
		&i.Seat,
		&i.TopSpeed,
		&i.MaxPower,
		&i.Pintu,
		&i.Gigi,
		&i.CreatedAt,
	)
	return i, err
}

const getMobilJoinMany = `-- name: GetMobilJoinMany :many
select m.nama, k.nama_kategori, u.username, gm.url  
from mobil m
inner join kategori k on m.kategori_id  = k.id
inner join users u on u.username = m.user_id 
inner join gambar_mobil gm on gm.mobil_id  = m.id
where m.nama LIKE $1
limit $2
Offset $3
`

type GetMobilJoinManyParams struct {
	Nama   string `json:"nama"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type GetMobilJoinManyRow struct {
	Nama         string         `json:"nama"`
	NamaKategori string         `json:"nama_kategori"`
	Username     string         `json:"username"`
	Url          sql.NullString `json:"url"`
}

func (q *Queries) GetMobilJoinMany(ctx context.Context, arg GetMobilJoinManyParams) ([]GetMobilJoinManyRow, error) {
	rows, err := q.db.QueryContext(ctx, getMobilJoinMany, arg.Nama, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMobilJoinManyRow{}
	for rows.Next() {
		var i GetMobilJoinManyRow
		if err := rows.Scan(
			&i.Nama,
			&i.NamaKategori,
			&i.Username,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
